from graphviz import Digraph
G = Digraph(comment='Causal Graph')
G.node('0','Breathing Difficulties', image='LungCancer_BreathingDifficulties.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('1','Loss of appetite', image='Treatable_Lossofappetite.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('2','Lung Cancer', image='LungCancer_Death.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('3','Pain', image='LungCancer_Pain.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('4','Radiation Therapy', image='LungCancer_RadiationTherapy.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('5','Collect Fluid', image='LungCancer_CollectFluid.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('6','Secondhand Smoke', image='SecondhandSmoke_LungCancer.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('7','Bone Pain', image='LungCancer_BonePain.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('8','Bleeding', image='LungCancer_Bleeding.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('9','Heavy Smoking', image='HeavySmoking_LungCancer.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('10','Symptoms', image='LungCancer_Symptoms.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('11','Treatable', image='Treatable_Lossofappetite.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('12','Death', image='LungCancer_Death.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('13','Complications', image='LungCancer_Complications.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('14','Workplace', image='Workplace_LungCancer.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('15','Speech Difficulties', image='LungCancer_SpeechDifficulties.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('16','Radon Gas', image='RadonGas_LungCancer.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('17','Fatigue', image='Treatable_Fatigue.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('18','Tobacco Use', image='TobaccoUse_LungCancer.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('19','Chemical Imbalances', image='LungCancer_ChemicalImbalances.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.node('20','Metastasize', image='LungCancer_Metastasize.txt.jpg', imagepos='ml', width='4', labelloc='b', shape='circle')
G.edge('18','2', label='often', **{'penwidth':'2.7'})
G.edge('6','2', label='occasionally', **{'penwidth':'2.2'})
G.edge('9','2', label='constantly', **{'penwidth':'1.2'})
G.edge('2','13', label='occasionally', **{'penwidth':'1.1'})
G.edge('2','12', label='occasionally', **{'penwidth':'2.1'})
G.edge('2','10', label='occasionally', **{'penwidth':'1.5'})
G.edge('2','7', label='usually', **{'penwidth':'1.2'})
G.edge('2','11', label='always', **{'penwidth':'1.1'})
G.edge('2','4', label='always', **{'penwidth':'1.1'})
G.edge('2','8', label='always', **{'penwidth':'1.1'})
G.edge('2','19', label='always', **{'penwidth':'1.1'})
G.edge('2','3', label='occasionally', **{'penwidth':'1.1'})
G.edge('2','15', label='always', **{'penwidth':'1.1'})
G.edge('2','0', label='occasionally', **{'penwidth':'1.1'})
G.edge('2','20', label='occasionally', **{'penwidth':'1.1'})
G.edge('2','5', label='occasionally', **{'penwidth':'1.1'})
G.edge('11','17', label='always', **{'penwidth':'1.1'})
G.edge('11','1', label='always', **{'penwidth':'1.1'})
G.edge('14','2', label='occasionally', **{'penwidth':'1.3'})
G.edge('16','2', label='regularly', **{'penwidth':'1.7'})
G.render('causal_graph')
