from graphviz import Digraph

#We arrange the graph using Networkx and then paint it using Cytoscape.
G = Digraph(comment="Lung Cancer Experiment")
G.node('1', "Tobacco Use")
G.node('2', "Lung Cancer")
G.node('3', "Secondhand Smoke")
G.node('4', "Heavy Smoking")
G.node('5', "Complications")
G.node('6', "Death")
G.node('7', "Symptoms")
G.node('8', "Bone Pain")
G.node('9', "Treatable")
G.node('10',"Radiation Therapy")
G.node('11',"Bleeding")
G.node('12',"Chemical Imbalances")
G.node('13',"Pain")
G.node('14',"Speech Difficulties")
G.node('15',"Breathing Difficulties")
G.node('16',"Metastasize")
G.node('17',"Collect Fluid")
G.node('19',"Fatigue")
G.node('20',"Loss of appetite")
G.node('21',"Workplace")
G.node('22',"Radon Gas")
G.edge('1','2')
G.edge('3','2')
G.edge('4','2')
G.edge('2','5')
G.edge('2','5')
G.edge('2','6')
G.edge('2','7')
G.edge('2','8')
G.edge('2','9')
G.edge('2','10')
G.edge('2','11')
G.edge('2','12')
G.edge('2','13')
G.edge('2','14')
G.edge('2','15')
G.edge('2','16')
G.edge('2','17')
G.edge('9','19')
G.edge('9','20')
G.edge('21','2')
G.edge('22','2')
G.render("causal_graph")
